--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 17.5 (Debian 17.5-1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: RequestImages; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."RequestImages" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "RequestId" text NOT NULL
);


ALTER TABLE public."RequestImages" OWNER TO admin;

--
-- Name: RequestImages_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."RequestImages" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RequestImages_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RequestManagements; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."RequestManagements" (
    "RequestId" text NOT NULL,
    "Notes" text NOT NULL,
    "RangeMin" integer NOT NULL,
    "RangeMax" integer NOT NULL,
    "RegistrationCost" numeric NOT NULL,
    "TransportCost" numeric NOT NULL,
    "PurchasePrice" numeric NOT NULL,
    "SalePrice" numeric NOT NULL,
    "RequestCloseReason" integer NOT NULL,
    "FinalOutcome" integer,
    CONSTRAINT "CK_FinalOutcome_Valid" CHECK ((("FinalOutcome" IS NULL) OR ("FinalOutcome" = ANY (ARRAY[10, 20, 30]))))
);


ALTER TABLE public."RequestManagements" OWNER TO admin;

--
-- Name: RequestOffers; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."RequestOffers" (
    "Id" integer NOT NULL,
    "RequestId" text NOT NULL,
    "OfferDescription" text NOT NULL,
    "OfferPrice" numeric NOT NULL,
    "OfferDate" timestamp with time zone NOT NULL
);


ALTER TABLE public."RequestOffers" OWNER TO admin;

--
-- Name: RequestOffers_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."RequestOffers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RequestOffers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RequestStatuses; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."RequestStatuses" (
    "Id" integer NOT NULL,
    "RequestId" text NOT NULL,
    "Status" integer NOT NULL,
    "ChangeDate" timestamp with time zone NOT NULL,
    "Notes" text
);


ALTER TABLE public."RequestStatuses" OWNER TO admin;

--
-- Name: RequestStatuses_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."RequestStatuses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RequestStatuses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Requests; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Requests" (
    "Id" text NOT NULL,
    "DateTime" timestamp with time zone NOT NULL,
    "LicensePlate" text NOT NULL,
    "Km" integer NOT NULL,
    "Make" text NOT NULL,
    "Model" text NOT NULL,
    "RegistrationYear" integer NOT NULL,
    "EngineSize" integer NOT NULL,
    "FuelType" integer NOT NULL,
    "TransmissionType" integer NOT NULL,
    "CarCondition" integer NOT NULL,
    "EngineCondition" integer NOT NULL,
    "InteriorConditions" text NOT NULL,
    "ExteriorConditions" text NOT NULL,
    "MechanicalConditions" text,
    "Cap" text NOT NULL,
    "City" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "DesiredPrice" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Requests" OWNER TO admin;

--
-- Name: Users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Users" (
    id integer NOT NULL,
    username character varying(50) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public."Users" OWNER TO admin;

--
-- Name: Users_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public."Users_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Users_id_seq" OWNER TO admin;

--
-- Name: Users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public."Users_id_seq" OWNED BY public."Users".id;


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO admin;

--
-- Name: Users id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Users" ALTER COLUMN id SET DEFAULT nextval('public."Users_id_seq"'::regclass);


--
-- Name: RequestImages PK_RequestImages; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."RequestImages"
    ADD CONSTRAINT "PK_RequestImages" PRIMARY KEY ("Id");


--
-- Name: RequestManagements PK_RequestManagements; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."RequestManagements"
    ADD CONSTRAINT "PK_RequestManagements" PRIMARY KEY ("RequestId");


--
-- Name: RequestOffers PK_RequestOffers; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."RequestOffers"
    ADD CONSTRAINT "PK_RequestOffers" PRIMARY KEY ("Id");


--
-- Name: RequestStatuses PK_RequestStatuses; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."RequestStatuses"
    ADD CONSTRAINT "PK_RequestStatuses" PRIMARY KEY ("Id");


--
-- Name: Requests PK_Requests; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Requests"
    ADD CONSTRAINT "PK_Requests" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: Users Users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY (id);


--
-- Name: Users Users_username_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_username_key" UNIQUE (username);


--
-- Name: IX_RequestImages_RequestId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_RequestImages_RequestId" ON public."RequestImages" USING btree ("RequestId");


--
-- Name: IX_RequestOffers_RequestId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_RequestOffers_RequestId" ON public."RequestOffers" USING btree ("RequestId");


--
-- Name: IX_RequestStatuses_RequestId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_RequestStatuses_RequestId" ON public."RequestStatuses" USING btree ("RequestId");


--
-- Name: RequestImages FK_RequestImages_Requests_RequestId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."RequestImages"
    ADD CONSTRAINT "FK_RequestImages_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES public."Requests"("Id") ON DELETE CASCADE;


--
-- Name: RequestManagements FK_RequestManagements_Requests_RequestId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."RequestManagements"
    ADD CONSTRAINT "FK_RequestManagements_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES public."Requests"("Id") ON DELETE CASCADE;


--
-- Name: RequestOffers FK_RequestOffers_Requests_RequestId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."RequestOffers"
    ADD CONSTRAINT "FK_RequestOffers_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES public."Requests"("Id") ON DELETE CASCADE;


--
-- Name: RequestStatuses FK_RequestStatuses_Requests_RequestId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."RequestStatuses"
    ADD CONSTRAINT "FK_RequestStatuses_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES public."Requests"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

